name: Amazon Selenium Tests

on:
  push:
    branches:
      - main  # O la rama que uses
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest  # Usa Ubuntu como entorno de ejecución

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Descarga el código del repositorio

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Usa OpenJDK (Eclipse Temurin)
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew  # Asegura que `gradlew` tenga permisos de ejecución

      - name: Verify Gradle version
        run: ./gradlew --version  # Verifica que Gradle 8.12 esté instalado correctamente

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          sudo apt install -y chromium-chromedriver
          which chromedriver
          chromedriver --version

      - name: Amazon Selenium Tests
        run: ./gradlew clean test -Dcucumber.publish.enabled=true -Dcucumber.publish.token=${{ secrets.CUCUMBER_PUBLISH_TOKEN }}